# Define a imagem base
FROM golang:1.21.5 as builder

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos do módulo Go e baixa as dependências
COPY go.mod go.sum ./
RUN go mod download

# Copia o código fonte da aplicação para o diretório de trabalho
COPY . .

# Compila a aplicação para um binário estático
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o crebito .

# Etapa 2: Montar a imagem final
# Utiliza uma imagem Docker "scratch" como base para uma imagem leve
FROM scratch

# Copia o binário estático da etapa de construção para a imagem final
COPY --from=builder /app/crebito /crebito

# Expõe a porta que a aplicação utiliza
EXPOSE 8080

# Define o comando para executar a aplicação
CMD ["/crebito"]    
    


